<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLeteqaw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLeteqaw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLeteqaw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLeteqaw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLeteqaw\appProdProjectContainer([
    'container.build_hash' => 'Leteqaw',
    'container.build_id' => 'bfd46f5a',
    'container.build_time' => 1560008241,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLeteqaw');
